"""In-memory store adapter — identical semantics to SQLite, no durability."""
from __future__ import annotations

from typing import Any

from ..domain.models import Attempt, DlqEntry, EventMsg, Lease, Namespace, Node, Token, Workflow, Workload
from ..ports.store import Store


class MemoryStore(Store):
    """Single-writer in-memory store. Durability is a no-op; used by tests and
    ephemeral deployments. All invariants (snapshot swap, index maintenance)
    are inherited from Store."""

    def open(self) -> None:
        self._snapshot.meta.setdefault("schema_version", 1)

    def close(self) -> None:
        return None

    # No-op persistence hooks ------------------------------------------------
    def _persist_meta(self, key: str, value: Any) -> None: ...
    def _persist_namespace(self, ns: Namespace) -> None: ...
    def _persist_token(self, token: Token) -> None: ...
    def _persist_workload(self, wl: Workload) -> None: ...
    def _persist_node(self, node: Node) -> None: ...
    def _persist_lease(self, lease: Lease) -> None: ...
    def _persist_workflow(self, wf: Workflow) -> None: ...
    def _persist_attempt(self, a: Attempt) -> None: ...
    def _persist_event(self, ev: EventMsg) -> None: ...
    def _persist_offset(self, group: str, topic: str, partition: int, seq: int) -> None: ...
    def _persist_dlq(self, entry: DlqEntry) -> None: ...
    def _persist_idempotency(self, key: str, request_hash: str, status: int, body: dict) -> None: ...
    def _persist_audit(self, entry: dict[str, Any]) -> None: ...
    def _persist_delete(self, table: str, key: tuple[str, str]) -> None: ...
